### PR TITLE
Update to latest cdt-gdb-vscode

### PR DESCRIPTION
**Pull request by jonahgraham**
This picks up many fixes and improvements that have been made to cdt-gdb-adapter

### CODE REVIEW

**Comment by jonahgraham** [comment]
ping on this review.

**Review by planger — APPROVED** [review]
Thank you very much, @jonahgraham! Sorry for the delay.
I just tested with the CMake Example and debugging still works like a charm.
Thanks again!

**Comment by GitMensch** [comment]
Note: when opening the CDT blueprint on the Theia website the debug extension is active - but there's no gdb in PATH, which seems quite bad.

**Comment by jonahgraham** [comment]
> Note: when opening the CDT blueprint on the Theia website the debug extension is active - but there's no gdb in PATH, which seems quite bad.

100% - raised #46

**Pull request merged**
