### PR TITLE
Integrate latest Theia Blueprint changes and update C++ dependencies

### PR DESCRIPTION
**Pull request by sdirix**
#### What it does

Updating CDT.cloud Blueprint to the latest state of Theia Blueprint (`706916e`).
Also updates the traceviewer extension and CMake plugins and integrates the
clangd contexts example VS Code extension.

Contributed on behalf of STMicroelectronics

#### How to test

Run CDT.cloud Blueprint

### CODE REVIEW

**Review by planger — APPROVED** [review]
Very nice! Tested it via electron app and welcome page, c editing, building and debugging works fine.
However, I get the following error when trying to open a trace:

```
root ERROR Request startTraceServer failed with error: ENOENT: no such file or directory, stat '/home/philip/Git/OpenSource/cdt-cloud/cdt-cloud-blueprint/node_modules/electron/dist/resources/trace-compass-server/tracecompass-server' Error: ENOENT: no such file or directory, stat '/home/philip/Git/OpenSource/cdt-cloud/cdt-cloud-blueprint/node_modules/electron/dist/resources/trace-compass-server/tracecompass-server'
```

Looks like trace compass is trying to start the server from a weird place.
However, I guess if trace compass server is already running on 8080, this error wouldn't appear.

However, I think we should create a follow-up ticket to ensure that this server is already bundled with electron app so that it can be started in the electron case.

For the browser case in the devcontainer this should be taken care of already.

**Comment by sdirix** [comment]
At the moment we don't bundle any "dependencies" with the Electron app, e.g. you also need a C++ toolchain and CMake on your system. I always start the TraceViewer server manually too.

The clangd extension is able to download clangd itself. So maybe we should suggest that for the trace viewer extension too, that's probably the cleanest solution.

**Comment by planger** [comment]
> The clangd extension is able to download clangd itself. So maybe we should suggest that for the trace viewer extension too, that's probably the cleanest solution.

Yeah, I agree. Anyway, we should definitely do something about that soon. I think we can't expect a user to figure out what to do and adding it to the welcome page would more and more glutter it.

**Comment by sdirix** [comment]
Rebased on master and replicated the changes for the Browser application

**Review by planger — APPROVED** [review]
Thanks, looks good to me! :+1:

**Comment by sdirix** [comment]
@planger I switched to the development build of the browser application because the Windows CI build always ran out of memory during the `theia build`. Is that fine for you?

**Comment by planger** [comment]
> @planger I switched to the development build of the browser application because the Windows CI build always ran out of memory during the `theia build`. Is that fine for you?

Sure, thanks a lot!

**Pull request merged**
