### PR TITLE
Update CDT Cloud Blueprint to 1.52.0

### LINKED ISSUE #93: Update to Theia IDE 1.52.0
Update and release aligned with Theia 1.52.0

## Required Steps

- [x] Merge latest Theia Blueprint community release commit
- [x] if required: Update Theia to latest version of said community release
- [x] Update all consumed Theia extensions and VSCode extensions
- [x] Test packaged Electron Blueprint locally
- [x] Test Browser variant locally
- [x] Test Docker variant locally
- [x] Run E2E tests locally (https://github.com/eclipse-cdt-cloud/cdt-cloud-blueprint?tab=readme-ov-file#running-e2e-tests)

After Merge

- [x] Verify that [Jenkins pipeline](https://ci.eclipse.org/theia/job/TheiaCDTCloud/job/master/) completed successfully
- [x] [Download a previous release](https://download.eclipse.org/theia/cdt-cloud/) and check that update to latest version completes successfully

Deploy to try.theia-cloud.io:

- [x] Push docker image with version tag to registry via [GH action](https://github.com/eclipse-cdt-cloud/cdt-cloud-blueprint/actions/workflows/publish-image.yml)
- [x] Update [deployment file](https://github.com/eclipsesource/try-theia-cloud-deployment/blob/main/resources/appdefinitions/cdt.yaml) to use newly pushed docker image
- [x] Apply the [deployment file](https://github.com/eclipsesource/try-theia-cloud-deployment/blob/main/resources/appdefinitions/cdt.yaml) to the cluster
- [x] Verify that updated [CDT Cloud Blueprint Try Online](https://try.theia-cloud.io/?appDef=cdt-cloud-demo) is available and works

Release announcement:

- [x] Announce release on the [cdt-cloud-dev](https://accounts.eclipse.org/mailing-list/cdt-cloud-dev) mailing list

### PR DESCRIPTION
**Pull request by jfaltermeier**
#### What it does

- Merge Theia Blueprint/IDE 1.52 release
- Adapt code base where necessary
- Update dependencies
- Update vs code extensions

Contributed on behalf of STMicroelectronics

closes #93

#### How to test

See instructions on #93

### CODE REVIEW

**Comment by jfaltermeier** [comment]
One thing I noticed during local testing is that `build.sh` in the context example wasn’t executable for me. I had to run `chmod +x`. Not sure if this is already known or a new issue.

**Comment by sdirix** [comment]
> One thing I noticed during local testing is that `build.sh` in the context example wasn’t executable for me. I had to run `chmod +x`. Not sure if this is already known or a new issue.

In the current version of Try Online it works out of the box

**Comment by jfaltermeier** [comment]
> > One thing I noticed during local testing is that `build.sh` in the context example wasn’t executable for me. I had to run `chmod +x`. Not sure if this is already known or a new issue.
> 
> In the current version of Try Online it works out of the box

Ah yes, it’s working in the Docker image but not with the browser or Electron application on my machine. So it might be something with my setup.

**Comment by jfaltermeier** [comment]
Sorry, one more force push, because of additional "" in the yarn.lock

**Review by sdirix — APPROVED** [review]

**Pull request merged**
